Until "Going back the the controller test" section
At this point i get this error instead of what Lesse said in his (great) post:

    colgado@waati ~/src/elixir/TDD/test-driving-a-phoenix-endpoint-app $ mix test test/contexts
    Compiling 15 files (.ex)
    warning: variable user is unused
      web/controllers/user_controller.ex:5

    == Compilation error on file web/controllers/user_controller.ex ==
    ** (CompileError) web/controllers/user_controller.ex:5: undefined function params/0
        (stdlib) lists.erl:1338: :lists.foreach/2
        (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

    colgado@waati ~/src/elixir/TDD/test-driving-a-phoenix-endpoint-app $

In fact this error appeared before, but i commented that line in order to continue learning.

Now that line is suppouse to be uncommented :( and in fact the reason of this repo existence)

Learning time!! :)